leftnav:
- identifier: 87e218ac-cd9e-20c9-12f2-f74132078c23
  name: 'Part 1: Fundamentals of Materials Structure'
  url: /pages/syllabus
  weight: 10
- identifier: external-bba3133091a24e888cdbcd096f3a11a8
  name: 'Part 1: Fundamentals of Materials Structure'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.1x+1T2019/about
  weight: 1000
- identifier: external-021b998e4c4c40eca5281354fb0a19c2
  name: 'Part 2: The Crystalline State'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.2x+1T2019/about
  weight: 1010
- identifier: external-3b5bf589820d4dc59e0b7d016abff356
  name: 'Part 3: Liquid Crystals, Defects, and Diffusion'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.3x+1T2019/about
  weight: 1020
