leftnav:
- identifier: 87e218ac-cd9e-20c9-12f2-f74132078c23
  name: 'Part 1: Fundamentals of Materials Structure'
  url: /pages/syllabus
  weight: 10
- identifier: external-934b262a4f254f5bb6f7f464bee91f0d
  name: 'Part 1: Fundamentals of Materials Structure'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.1x+1T2019/about
  weight: 1000
- identifier: external-0ee1a4d5f2bf4e1386d12cfa80bd19ed
  name: 'Part 2: The Crystalline State'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.2x+1T2019/about
  weight: 1010
- identifier: external-707c01e988564beb9f2b5003f033ccd9
  name: 'Part 3: Liquid Crystals, Defects, and Diffusion'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.3x+1T2019/about
  weight: 1020
